# Site/SEO settings
email: av0id.biz@gmail.com
baseurl: ""
permalink: /:year/:title/
google_analytics: UA-30039942-2

name: Niki the Low
title: НОВА ДЕГЕНЕРАЦИЯ
description: >
  Малък уебзайн за изкуство, философия, критическа теория и окултура, подържан от Никола Стоянов.
url: https://newdegeneration.netlify.app
twitter_username: avoid1
default_img: /assets/images/seo.png
social:
  - name: twitter
    url: https://twitter.com/avoid1
  - name: instagram
    url: https://www.instagram.com/avoid_nd
  - name: facebook
    url: https://www.facebook.com/av0id.nd

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/V_62QlIt-Ik-

# Disqus settings
disqus: zasegane

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ники Долния
    bio: Някво типче с амбиций идващ от долу.

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Нова Дегенерация - Тагове'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
    clippings: all
    comments: all
    startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor